version: '3.7'

services:
  influx:
    image: influxdb:1.7
    container_name: rest-benchmark-influx
    ports:
      - "8086:8086"

  telegraf:
    build: .
    container_name: rest-benchmark-telegraf