version: '3.7'

services:
    postgres:
        build: .
        container_name: postgres
        environment:
            - POSTGRES_PASSWORD=foobar
            - POSTGRES_DB=bench
        ports:
            - "45432:5432"
