version: '3.7'

services:
  grafana:
    build: .
    container_name: grafana
    ports:
      - "43000:3000"
    # volumes:
    #   - "$PWD/data:/var/lib/grafana"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
